const express=require('express'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),cors=require('cors'),path=require('path'),{Pool}=require('pg');
const app=express(),PORT=process.env.PORT||3001,JWT_SECRET=process.env.JWT_SECRET||'sproutlings2024';
app.use(cors({origin:'*'}));app.use(express.json({limit:'5mb'}));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
async function query(sql,params=[]){const c=await pool.connect();try{const r=await c.query(sql,params);return r.rows}finally{c.release()}}
async function queryOne(sql,params=[]){const r=await query(sql,params);return r[0]||null}
async function initDb(){
await query(`CREATE TABLE IF NOT EXISTS staff(id SERIAL PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT DEFAULT 'staff',created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT*1000);CREATE TABLE IF NOT EXISTS children(id SERIAL PRIMARY KEY,name TEXT NOT NULL,age INTEGER,initials TEXT,color TEXT DEFAULT '#3A8C6E',parents TEXT,emergency_contact TEXT,notes TEXT,pin TEXT,photo TEXT,active INTEGER DEFAULT 1,created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT*1000);CREATE TABLE IF NOT EXISTS attendance(id SERIAL PRIMARY KEY,child_id INTEGER NOT NULL,date TEXT NOT NULL,check_in BIGINT,check_out BIGINT,who TEXT);CREATE TABLE IF NOT EXISTS daily_logs(id SERIAL PRIMARY KEY,child_id INTEGER NOT NULL,date TEXT NOT NULL,type TEXT NOT NULL,note TEXT,created_by TEXT,created_at BIGINT DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT*1000);`);
const s=await queryOne('SELECT id FROM staff LIMIT 1');
if(!s){await query(`INSERT INTO staff(username,password_hash,role)VALUES($1,$2,'admin')`,[' admin',bcrypt.hashSync('admin1234',10)]);console.log('Admin created');}
console.log('DB ready');}
function auth(req,res,next){const t=req.headers.authorization?.split(' ')[1];if(!t)return res.status(401).json({error:'No token'});try{req.user=jwt.verify(t,JWT_SECRET);next();}catch{res.status(401).json({error:'Invalid token'});}}
function adminOnly(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin only'});next();}
app.post('/api/auth/login',async(req,res)=>{try{const{username,password}=req.body;const s=await queryOne('SELECT * FROM staff WHERE username=$1',[username]);if(!s||!bcrypt.compareSync(password,s.password_hash))return res.status(401).json({error:'Invalid credentials'});const token=jwt.sign({id:s.id,username:s.username,role:s.role},JWT_SECRET,{expiresIn:'12h'});res.json({token,user:{id:s.id,username:s.username,role:s.role}});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/children',async(_,res)=>{try{res.json(await query('SELECT id,name,age,initials,color,pin FROM children WHERE active=1 ORDER BY name'));}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/children/full',auth,async(_,res)=>{try{res.json(await query('SELECT * FROM children WHERE active=1 ORDER BY name'));}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/children',auth,async(req,res)=>{try{const{name,age,initials,color,parents,emergency_contact,notes,pin,photo}=req.body;if(!name)return res.status(400).json({error:'Name required'});const ini=initials||name.split(' ').map(w=>w[0]).join('').toUpperCase().slice(0,2);const r=await query(`INSERT INTO children(name,age,initials,color,parents,emergency_contact,notes,pin,photo)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)RETURNING id`,[name,age||null,ini,color||'#3A8C6E',parents||'',emergency_contact||'',notes||'',pin||'',photo||null]);res.json({id:r[0].id});}catch(e){res.status(500).json({error:e.message});}});
app.put('/api/children/:id',auth,async(req,res)=>{try{const{name,age,initials,color,parents,emergency_contact,notes,pin,photo}=req.body;await query(`UPDATE children SET name=$1,age=$2,initials=$3,color=$4,parents=$5,emergency_contact=$6,notes=$7,pin=$8,photo=$9 WHERE id=$10`,[name,age||null,initials,color,parents||'',emergency_contact||'',notes||'',pin||'',photo||null,req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/children/:id',auth,adminOnly,async(req,res)=>{try{await query('UPDATE children SET active=0 WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/kiosk/verify-pin',async(req,res)=>{try{const{childId,pin}=req.body;const c=await queryOne('SELECT pin FROM children WHERE id=$1',[childId]);if(!c)return res.status(404).json({error:'Not found'});res.json({valid:!c.pin||c.pin===pin});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/attendance/checkin',async(req,res)=>{try{const{childId,who}=req.body;const today=new Date().toISOString().slice(0,10);const now=Date.now();const r=await query(`INSERT INTO attendance(child_id,date,check_in,who)VALUES($1,$2,$3,$4)RETURNING id`,[childId,today,now,who||'']);res.json({id:r[0].id,checkIn:now});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/attendance/checkout',async(req,res)=>{try{const{childId,who}=req.body;const today=new Date().toISOString().slice(0,10);const now=Date.now();const open=await queryOne(`SELECT id FROM attendance WHERE child_id=$1 AND date=$2 AND check_out IS NULL ORDER BY check_in DESC LIMIT 1`,[childId,today]);if(!open)return res.status(400).json({error:'No open check-in'});await query(`UPDATE attendance SET check_out=$1,who=$2 WHERE id=$3`,[now,who||'',open.id]);res.json({ok:true,checkOut:now});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/attendance/today',async(_,res)=>{try{const today=new Date().toISOString().slice(0,10);res.json(await query(`SELECT a.*,c.name,c.initials,c.color,c.age FROM attendance a JOIN children c ON a.child_id=c.id WHERE a.date=$1 ORDER BY a.check_in DESC`,[today]));}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/attendance/history',auth,async(req,res)=>{try{const{child_id,date_from,date_to,limit=200}=req.query;let q=`SELECT a.*,c.name,c.initials,c.color FROM attendance a JOIN children c ON a.child_id=c.id WHERE 1=1`;const p=[];if(child_id){p.push(child_id);q+=` AND a.child_id=$${p.length}`;}if(date_from){p.push(date_from);q+=` AND a.date>=$${p.length}`;}if(date_to){p.push(date_to);q+=` AND a.date<=$${p.length}`;}p.push(Number(limit));q+=` ORDER BY a.date DESC,a.check_in DESC LIMIT $${p.length}`;res.json(await query(q,p));}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/attendance/:id',auth,async(req,res)=>{try{await query('DELETE FROM attendance WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.put('/api/attendance/:id',auth,async(req,res)=>{try{const{check_in,check_out,who}=req.body;await query('UPDATE attendance SET check_in=$1,check_out=$2,who=$3 WHERE id=$4',[check_in||null,check_out||null,who||'',req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/logs',auth,async(req,res)=>{try{const{date,child_id}=req.query;let q=`SELECT l.*,c.name,c.initials,c.color FROM daily_logs l JOIN children c ON l.child_id=c.id WHERE 1=1`;const p=[];if(date){p.push(date);q+=` AND l.date=$${p.length}`;}if(child_id){p.push(child_id);q+=` AND l.child_id=$${p.length}`;}res.json(await query(q+' ORDER BY l.created_at DESC',p));}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/logs',auth,async(req,res)=>{try{const{childId,date,type,note}=req.body;if(!childId||!note)return res.status(400).json({error:'childId and note required'});const r=await query(`INSERT INTO daily_logs(child_id,date,type,note,created_by,created_at)VALUES($1,$2,$3,$4,$5,$6)RETURNING id`,[childId,date||new Date().toISOString().slice(0,10),type||'note',note,req.user.username,Date.now()]);res.json({id:r[0].id});}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/logs/:id',auth,async(req,res)=>{try{await query('DELETE FROM daily_logs WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/staff',auth,adminOnly,async(_,res)=>{try{res.json(await query('SELECT id,username,role,created_at FROM staff ORDER BY id'));}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/staff',auth,adminOnly,async(req,res)=>{try{const{username,password,role}=req.body;if(!username||!password)return res.status(400).json({error:'Required'});const r=await query(`INSERT INTO staff(username,password_hash,role,created_at)VALUES($1,$2,$3,$4)RETURNING id`,[username,bcrypt.hashSync(password,10),role||'staff',Date.now()]);res.json({id:r[0].id});}catch(e){res.status(400).json({error:'Username exists'});}});
app.delete('/api/staff/:id',auth,adminOnly,async(req,res)=>{try{await query('DELETE FROM staff WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.put('/api/staff/:id/password',auth,async(req,res)=>{try{const{newPassword}=req.body;if(!newPassword||newPassword.length<4)return res.status(400).json({error:'Min 4 chars'});await query('UPDATE staff SET password_hash=$1 WHERE id=$2',[bcrypt.hashSync(newPassword,10),req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/reports/attendance-csv',auth,async(req,res)=>{try{const{date_from,date_to,child_id}=req.query;let q=`SELECT a.date,c.name,c.age,a.check_in,a.check_out,a.who FROM attendance a JOIN children c ON a.child_id=c.id WHERE 1=1`;const p=[];if(child_id){p.push(child_id);q+=` AND a.child_id=$${p.length}`;}if(date_from){p.push(date_from);q+=` AND a.date>=$${p.length}`;}if(date_to){p.push(date_to);q+=` AND a.date<=$${p.length}`;}const rows=await query(q+' ORDER BY a.date DESC,c.name',p);const ft=ts=>ts?new Date(Number(ts)).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'';const fd=(a,b)=>a&&b?Math.round((Number(b)-Number(a))/60000)+' min':'';let csv='Date,Child,Age,Check In,Check Out,Duration,By\n';rows.forEach(r=>{csv+=`${r.date},"${r.name}",${r.age||''},${ft(r.check_in)},${ft(r.check_out)},${fd(r.check_in,r.check_out)},"${r.who||''}"\n`;});res.setHeader('Content-Type','text/csv');res.setHeader('Content-Disposition',`attachment; filename=attendance_${new Date().toISOString().slice(0,10)}.csv`);res.send(csv);}catch(e){res.status(500).json({error:e.message});}});
if(process.env.NODE_ENV==='production'){const dist=path.join(__dirname,'../dist');app.use(express.static(dist));app.get('*',(_,res)=>res.sendFile(path.join(dist,'index.html')));}
initDb().then(()=>app.listen(PORT,()=>console.log(`\n🌱 Sproutlings on port ${PORT}\n`))).catch(err=>{console.error(err);process.exit(1);});
